# Generated by Django 5.0 on 2024-01-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_rename_review_review_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
