# Generated by Django 5.0 on 2024-01-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_address_order_address1_order_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
