# Generated by Django 5.0 on 2024-01-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
